
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed3;

	private global::Gtk.Label label11;

	private global::Gtk.Label label12;

	private global::Gtk.Label label13;

	private global::Gtk.Label label14;

	private global::Gtk.Label label15;

	private global::Gtk.Label label16;

	private global::Gtk.HSeparator hseparator1;

	private global::Gtk.Entry entry1;

	private global::Gtk.Entry entry2;

	private global::Gtk.Entry entry3;

	private global::Gtk.Entry entry4;

	private global::Gtk.Entry entry5;

	private global::Gtk.Entry entry6;

	private global::Gtk.Entry entry7;

	private global::Gtk.Label label1;

	private global::Gtk.Label label2;

	private global::Gtk.Button button2;

	private global::Gtk.Button button3;

	private global::Gtk.Button button4;

	private global::Gtk.Button button1;

	private global::Gtk.Label label4;

	private global::Gtk.Label label7;

	private global::Gtk.Label label8;

	private global::Gtk.Label label9;

	private global::Gtk.Label label17;

	private global::Gtk.Label label18;

	private global::Gtk.Label label19;

	private global::Gtk.Entry entry8;

	private global::Gtk.Label label3;

	private global::Gtk.Label label20;

	private global::Gtk.Label label21;

	private global::Gtk.Label label22;

	private global::Gtk.Label label23;

	private global::Gtk.Label label24;

	private global::Gtk.Label label25;

	private global::Gtk.Image image1;

	private global::Gtk.Image image2;

	private global::Gtk.Label label10;

	private global::Gtk.Label label5;

	private global::Gtk.Label label26;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed3 = new global::Gtk.Fixed();
		this.fixed3.Name = "fixed3";
		this.fixed3.HasWindow = false;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.label11 = new global::Gtk.Label();
		this.label11.WidthRequest = 31;
		this.label11.Name = "label11";
		this.label11.LabelProp = global::Mono.Unix.Catalog.GetString("Nom");
		this.fixed3.Add(this.label11);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label11]));
		w1.X = 100;
		w1.Y = 260;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.label12 = new global::Gtk.Label();
		this.label12.Name = "label12";
		this.label12.LabelProp = global::Mono.Unix.Catalog.GetString("Salaire Brut");
		this.fixed3.Add(this.label12);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label12]));
		w2.X = 100;
		w2.Y = 320;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.label13 = new global::Gtk.Label();
		this.label13.Name = "label13";
		this.label13.LabelProp = global::Mono.Unix.Catalog.GetString("Conjoint");
		this.fixed3.Add(this.label13);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label13]));
		w3.X = 100;
		w3.Y = 380;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.label14 = new global::Gtk.Label();
		this.label14.Name = "label14";
		this.label14.LabelProp = global::Mono.Unix.Catalog.GetString("Prénoms");
		this.fixed3.Add(this.label14);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label14]));
		w4.X = 690;
		w4.Y = 260;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.label15 = new global::Gtk.Label();
		this.label15.Name = "label15";
		this.label15.LabelProp = global::Mono.Unix.Catalog.GetString("Nbre de jours");
		this.fixed3.Add(this.label15);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label15]));
		w5.X = 690;
		w5.Y = 320;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.label16 = new global::Gtk.Label();
		this.label16.Name = "label16";
		this.label16.LabelProp = global::Mono.Unix.Catalog.GetString("Enfants");
		this.fixed3.Add(this.label16);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label16]));
		w6.X = 690;
		w6.Y = 380;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.hseparator1 = new global::Gtk.HSeparator();
		this.hseparator1.Name = "hseparator1";
		this.fixed3.Add(this.hseparator1);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.hseparator1]));
		w7.X = 620;
		w7.Y = 180;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.entry1 = new global::Gtk.Entry();
		this.entry1.WidthRequest = 265;
		this.entry1.CanFocus = true;
		this.entry1.Name = "entry1";
		this.entry1.IsEditable = true;
		this.entry1.InvisibleChar = '•';
		this.fixed3.Add(this.entry1);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.entry1]));
		w8.X = 210;
		w8.Y = 260;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.entry2 = new global::Gtk.Entry();
		this.entry2.WidthRequest = 265;
		this.entry2.CanFocus = true;
		this.entry2.Name = "entry2";
		this.entry2.IsEditable = true;
		this.entry2.InvisibleChar = '•';
		this.fixed3.Add(this.entry2);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.entry2]));
		w9.X = 210;
		w9.Y = 320;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.entry3 = new global::Gtk.Entry();
		this.entry3.WidthRequest = 265;
		this.entry3.CanFocus = true;
		this.entry3.Name = "entry3";
		this.entry3.IsEditable = true;
		this.entry3.InvisibleChar = '•';
		this.fixed3.Add(this.entry3);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.entry3]));
		w10.X = 210;
		w10.Y = 380;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.entry4 = new global::Gtk.Entry();
		this.entry4.WidthRequest = 265;
		this.entry4.CanFocus = true;
		this.entry4.Name = "entry4";
		this.entry4.IsEditable = true;
		this.entry4.InvisibleChar = '•';
		this.fixed3.Add(this.entry4);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.entry4]));
		w11.X = 830;
		w11.Y = 260;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.entry5 = new global::Gtk.Entry();
		this.entry5.WidthRequest = 265;
		this.entry5.CanFocus = true;
		this.entry5.Name = "entry5";
		this.entry5.IsEditable = true;
		this.entry5.InvisibleChar = '•';
		this.fixed3.Add(this.entry5);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.entry5]));
		w12.X = 830;
		w12.Y = 320;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.entry6 = new global::Gtk.Entry();
		this.entry6.WidthRequest = 265;
		this.entry6.CanFocus = true;
		this.entry6.Name = "entry6";
		this.entry6.IsEditable = true;
		this.entry6.InvisibleChar = '•';
		this.fixed3.Add(this.entry6);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.entry6]));
		w13.X = 830;
		w13.Y = 380;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.entry7 = new global::Gtk.Entry();
		this.entry7.WidthRequest = 265;
		this.entry7.HeightRequest = 50;
		this.entry7.CanFocus = true;
		this.entry7.Name = "entry7";
		this.entry7.IsEditable = true;
		this.entry7.InvisibleChar = '•';
		this.fixed3.Add(this.entry7);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.entry7]));
		w14.X = 830;
		w14.Y = 470;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("0 : Célibataire");
		this.fixed3.Add(this.label1);
		global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label1]));
		w15.X = 210;
		w15.Y = 470;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.label2 = new global::Gtk.Label();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("1 : Conjoint non salarié");
		this.fixed3.Add(this.label2);
		global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label2]));
		w16.X = 210;
		w16.Y = 500;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.button2 = new global::Gtk.Button();
		this.button2.WidthRequest = 160;
		this.button2.HeightRequest = 45;
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		this.button2.Label = global::Mono.Unix.Catalog.GetString("Annuler");
		this.fixed3.Add(this.button2);
		global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.button2]));
		w17.X = 360;
		w17.Y = 580;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.button3 = new global::Gtk.Button();
		this.button3.WidthRequest = 200;
		this.button3.HeightRequest = 45;
		this.button3.CanFocus = true;
		this.button3.Name = "button3";
		this.button3.UseUnderline = true;
		this.button3.Label = global::Mono.Unix.Catalog.GetString("Liste des employés");
		this.fixed3.Add(this.button3);
		global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.button3]));
		w18.X = 630;
		w18.Y = 580;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.button4 = new global::Gtk.Button();
		this.button4.WidthRequest = 160;
		this.button4.HeightRequest = 45;
		this.button4.CanFocus = true;
		this.button4.Name = "button4";
		this.button4.UseUnderline = true;
		this.button4.Label = global::Mono.Unix.Catalog.GetString("Quitter");
		this.fixed3.Add(this.button4);
		global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.button4]));
		w19.X = 930;
		w19.Y = 580;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.button1 = new global::Gtk.Button();
		this.button1.WidthRequest = 160;
		this.button1.HeightRequest = 45;
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString("Valider");
		this.fixed3.Add(this.button1);
		global::Gtk.Fixed.FixedChild w20 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.button1]));
		w20.X = 100;
		w20.Y = 580;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.label4 = new global::Gtk.Label();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Brut Fiscal Annuel");
		this.fixed3.Add(this.label4);
		global::Gtk.Fixed.FixedChild w21 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label4]));
		w21.X = 110;
		w21.Y = 730;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.label7 = new global::Gtk.Label();
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("Brut Fiscal Après Abattement");
		this.fixed3.Add(this.label7);
		global::Gtk.Fixed.FixedChild w22 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label7]));
		w22.X = 110;
		w22.Y = 780;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.label8 = new global::Gtk.Label();
		this.label8.Name = "label8";
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("IRPP avant réduction");
		this.fixed3.Add(this.label8);
		global::Gtk.Fixed.FixedChild w23 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label8]));
		w23.X = 110;
		w23.Y = 830;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.label9 = new global::Gtk.Label();
		this.label9.Name = "label9";
		this.label9.LabelProp = global::Mono.Unix.Catalog.GetString("IMPÔTS");
		this.fixed3.Add(this.label9);
		global::Gtk.Fixed.FixedChild w24 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label9]));
		w24.X = 110;
		w24.Y = 910;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.label17 = new global::Gtk.Label();
		this.label17.Name = "label17";
		this.label17.LabelProp = global::Mono.Unix.Catalog.GetString("Abattements");
		this.fixed3.Add(this.label17);
		global::Gtk.Fixed.FixedChild w25 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label17]));
		w25.X = 650;
		w25.Y = 730;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.label18 = new global::Gtk.Label();
		this.label18.Name = "label18";
		this.label18.LabelProp = global::Mono.Unix.Catalog.GetString("Nombre de parts");
		this.fixed3.Add(this.label18);
		global::Gtk.Fixed.FixedChild w26 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label18]));
		w26.X = 650;
		w26.Y = 780;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.label19 = new global::Gtk.Label();
		this.label19.Name = "label19";
		this.label19.LabelProp = global::Mono.Unix.Catalog.GetString("Réduction");
		this.fixed3.Add(this.label19);
		global::Gtk.Fixed.FixedChild w27 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label19]));
		w27.X = 650;
		w27.Y = 830;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.entry8 = new global::Gtk.Entry();
		this.entry8.WidthRequest = 265;
		this.entry8.HeightRequest = 50;
		this.entry8.CanFocus = true;
		this.entry8.Name = "entry8";
		this.entry8.IsEditable = true;
		this.entry8.InvisibleChar = '•';
		this.fixed3.Add(this.entry8);
		global::Gtk.Fixed.FixedChild w28 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.entry8]));
		w28.X = 650;
		w28.Y = 910;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.label3 = new global::Gtk.Label();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("XOF");
		this.fixed3.Add(this.label3);
		global::Gtk.Fixed.FixedChild w29 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label3]));
		w29.X = 390;
		w29.Y = 730;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.label20 = new global::Gtk.Label();
		this.label20.Name = "label20";
		this.label20.LabelProp = global::Mono.Unix.Catalog.GetString("XOF");
		this.fixed3.Add(this.label20);
		global::Gtk.Fixed.FixedChild w30 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label20]));
		w30.X = 390;
		w30.Y = 780;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.label21 = new global::Gtk.Label();
		this.label21.Name = "label21";
		this.label21.LabelProp = global::Mono.Unix.Catalog.GetString("XOF");
		this.fixed3.Add(this.label21);
		global::Gtk.Fixed.FixedChild w31 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label21]));
		w31.X = 390;
		w31.Y = 830;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.label22 = new global::Gtk.Label();
		this.label22.Name = "label22";
		this.label22.LabelProp = global::Mono.Unix.Catalog.GetString("XOF");
		this.fixed3.Add(this.label22);
		global::Gtk.Fixed.FixedChild w32 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label22]));
		w32.X = 830;
		w32.Y = 730;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.label23 = new global::Gtk.Label();
		this.label23.Name = "label23";
		this.label23.LabelProp = "XX";
		this.fixed3.Add(this.label23);
		global::Gtk.Fixed.FixedChild w33 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label23]));
		w33.X = 830;
		w33.Y = 780;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.label24 = new global::Gtk.Label();
		this.label24.Name = "label24";
		this.label24.LabelProp = global::Mono.Unix.Catalog.GetString("XOF");
		this.fixed3.Add(this.label24);
		global::Gtk.Fixed.FixedChild w34 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label24]));
		w34.X = 830;
		w34.Y = 830;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.label25 = new global::Gtk.Label();
		this.label25.Name = "label25";
		this.label25.LabelProp = global::Mono.Unix.Catalog.GetString("XOF");
		this.fixed3.Add(this.label25);
		global::Gtk.Fixed.FixedChild w35 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label25]));
		w35.X = 220;
		w35.Y = 910;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.image1 = new global::Gtk.Image();
		this.image1.Name = "image1";
		this.fixed3.Add(this.image1);
		global::Gtk.Fixed.FixedChild w36 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.image1]));
		w36.X = 73;
		w36.Y = 19;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.image2 = new global::Gtk.Image();
		this.image2.Name = "image2";
		this.fixed3.Add(this.image2);
		global::Gtk.Fixed.FixedChild w37 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.image2]));
		w37.X = 900;
		w37.Y = 19;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.label10 = new global::Gtk.Label();
		this.label10.Name = "label10";
		this.label10.LabelProp = global::Mono.Unix.Catalog.GetString("SIMULATION D\'IMPÔTS");
		this.fixed3.Add(this.label10);
		global::Gtk.Fixed.FixedChild w38 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label10]));
		w38.X = 539;
		w38.Y = 158;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.label5 = new global::Gtk.Label();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("République du Sénégal");
		this.label5.Justify = ((global::Gtk.Justification)(2));
		this.fixed3.Add(this.label5);
		global::Gtk.Fixed.FixedChild w39 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label5]));
		w39.X = 538;
		w39.Y = 104;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.label26 = new global::Gtk.Label();
		this.label26.Name = "label26";
		this.label26.LabelProp = global::Mono.Unix.Catalog.GetString("CopyRight (Mouhamed Diop Wade)");
		this.fixed3.Add(this.label26);
		global::Gtk.Fixed.FixedChild w40 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label26]));
		w40.X = 100;
		w40.Y = 207;
		this.Add(this.fixed3);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 1242;
		this.DefaultHeight = 978;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.button2.Clicked += new global::System.EventHandler(this.OnButton2Clicked);
		this.button3.Clicked += new global::System.EventHandler(this.OnButton3Clicked);
		this.button4.Clicked += new global::System.EventHandler(this.OnButton4Clicked);
		this.button1.Clicked += new global::System.EventHandler(this.OnButton1Clicked);
	}
}
